#server:
#  port: 9411
#
#spring:
#  profiles:
#    active: dev
#  sleuth:
#    enabled: false
#    sampler:
#      probability: 1.0
#
#zipkin:
#  collector:
#    rabbitmq:
#      addresses: 192.168.1.200:5672
#      username: admin
#      password: admin
#      queue: zipkin
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#  metrics:
#    web:
#      server:
#        auto-time-requests: false