zuul:
  routes:
    #配置路由规则（经典写法）
    #api-a:
      #path: /api-a/**
      #serviceId: lion-demo-consumer
    #api-b:
      #path: /api-b/**
      #serviceId: lion-demo-ribbon
    #配置路由规则（简化写法）
    lion-demo-provider: /demo/provider/**
    lion-demo-consumer: /demo/consumer/**
    lion-demo-ribbon: /demo/ribbon/**
    lion-demo-sample: /demo/sample/**
    lion-bigdata: /bigdata/**
    lion-blockchain: /blockchain/**
    lion-upms: /upms/**
    lion-auth: /auth/**
    #排除某些路由
    #ignored-patterns:
    #- /lion-demo-ribbon/init