language: java
sudo: false

jdk:
  - oraclejdk8

before_script:
  - chmod a+x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)