#server:
#  port: 8500
#
#spring:
#  cloud:
#    bus:
#      enabled: true
#      trace:
#        enabled: true
#  rabbitmq:
#    host: 192.168.1.200
#    port: 5672
#    username: admin
#    password: admin
#
#turbine:
#  aggregator:
#    cluster-config: default
#  # 配置 服务注册/发现中心 中的 serviceId 列表，指定要监控的服务，多个服务用“,”隔开
#  app-config: lion-zuul-server,lion-auth,lion-upms,lion-demo-provider,lion-demo-consumer,lion-demo-ribbon,lion-demo-sample
#  # 指定集群名称
#  cluster-name-expression: new String("default")
#  combine-host-port: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always