#server:
#  port: 8400
#
#spring:
#  cloud:
#    bus:
#      enabled: true
#      trace:
#        enabled: true
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#  rabbitmq:
#    host: 192.168.1.200
#    port: 5672
#    username: admin
#    password: admin
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    #base-url: http://localhost:9411
#    sender:
#      type: rabbit
#  redis:
#    host: 192.168.1.200
#    port: 6379
#security:
#  oauth2:
#    client:
#      client-id: lion_client
#      access-token-uri: http://localhost:${server.port}/auth/oauth/token
#      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
#    resource:
#      user-info-uri: http://localhost:${server.port}/auth/user/principal
#      prefer-token-info: false
#
#zuul:
#  host:
#    connect-timeout-millis: 15000
#    socket-timeout-millis: 60000
#  routes:
#    #配置路由规则（经典写法）
#    #api-a:
#      #path: /api-a/**
#      #serviceId: lion-demo-consumer
#    #api-b:
#      #path: /api-b/**
#      #serviceId: lion-demo-ribbon
#    #配置路由规则（简化写法）
#    lion-auth: /auth/**
#    lion-upms: /upms/**
#    lion-id: /id/**
#    lion-bigdata: /bigdata/**
#    lion-blockchain: /blockchain/**
#    lion-demo-provider: /demo/provider/**
#    lion-demo-consumer: /demo/consumer/**
#    lion-demo-sample: /demo/sample/**
#    lion-demo-ribbon: /demo/ribbon/**
#    #排除某些路由
#    #ignored-patterns:
#    #- /lion-demo-ribbon/init
#
##解决（504）Gateway Timeout，设置ribbon的超时时间小于zuul的超时时间
#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always