server:
  port: 8400

spring:
  application:
    name: lion-zuul-server
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.1.200
    port: 5672
    username: admin
    password: admin

security:
  oauth2:
    client:
      client-id: lion-zuul-server
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:${server.port}/auth/user/principal
      prefer-token-info: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always