server:
  port: 8782

spring:
  application:
    name: lion-demo-sample
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.1.200
    port: 5672
    username: admin
    password: admin
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit

security:
  oauth2:
    client:
      client-id: lion-zuul-server
      access-token-uri: http://localhost:8888/oauth/token
      user-authorization-uri: http://localhost:8888/oauth/authorize
    resource:
      user-info-uri: http://localhost:8888/user/principal
      prefer-token-info: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always